baseURL: "https://nibble2.github.io/"
title: nibble2
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true

DefaultContentLanguage: ko

languages:
  ko:
    languageName: "Korean"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

params:
  env: production
  title: https://nibble2.github.io
  author: nibble2

  images: ["papermod-cover.png"]

  ShowShareButtons: true
  comments: true
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecail1stPost: false

  assets:
    disableFingerprinting: true

  label:
    text: "Nibble 개발 블로그✨"

  homeInfoParams:
    Title: 이다나 | Lee da na
    Content: "안녕하세요 배우고 공유하는 개발자 이다나입니다.\n- 현재 Vue.js 프론트엔드 개발자로 일하고 있습니다.\n- 공부한 것을 바탕으로 느낀 점을 작성합니다.

  socialIcons:
    - name: "github"
      url: "https://nibble2.github.io/"
    - name: "email"
      url: "vanillaleedana@gmail.com"
