baseURL: "https://nibble2.github.io/"
title: nibble2
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true

DefaultContentLanguage: ko

languages:
  ko:
    languageName: "Korean"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

params:
  env: production
  title: https://nibble2.github.io
  author: nibble2

  images: ["papermod-cover.png"]

  ShowShareButtons: true
  comments: true
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecail1stPost: false

  assets:
    disableFingerprinting: true

  label:
    text: "Nibble ✨"

  homeInfoParams:
    Title: 이다나 | Lee da na
    Content: "안녕하세요 배우는 것을 좋아하는 개발자 이다나입니다.\n- 현재 백엔드 개발자로 취업 준비중이며 Javascript와 Node.js를 공부중입니다.\n- 매일 공부한 것을 바탕으로 느낀 점을 작성합니다. ✨\n- 현재 [노션](https://www.notion.so/nibble2/410272d4767f44d495534df32398ae29)에서 책 스터디를 진행중이며 [블로그](https://velog.io/@nibble)도 함께 운영하고 있습니다"

  socialIcons:
    - name: "github"
      url: "https://nibble2.github.io/"
    - name: "email"
      url: "vanillaleedana@gmail.com"
