baseURL = "https://nibble2.github.io/"
languageCode = "en-us"
title = "Nibble ✨"
theme = "paper"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
disqusShortname = "raeperd-github-io"
googleAnalytics = "UA-168674186-1"

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [
  "HTML",
  "RSS",
  "JSON"
]

[params]
  env = "production"
  [params.homeInfoParams]
  Title = "이다나 | Lee da na"
  Content = "안녕하세요 배우는 것을 좋아하는 개발자 이다나입니다.\n- 현재 백엔드 개발자로 취업 준비중이며 Javascript와 Node.js를 공부중입니다.\n- 매일 공부한 것을 바탕으로 느낀 점을 작성합니다. ✨\n- 현재 [노션](https://www.notion.so/nibble2/410272d4767f44d495534df32398ae29)에서 책 스터디를 진행중이며 [블로그](https://velog.io/@nibble)도 함께 운영하고 있습니다"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/nibble2"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/euepaal/"

[taxonomies]
  series = "series"
  about = 'about'
  tags = 'tags'

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1.0

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 10.0

  [[menu.main]]
  name = "Series"
  url = "/series/"
  weight = 10.0

  [[menu.main]]
  title = "Archive"
  url = "/post/"

[profileMode]
enabled = false
title = "raeperd.github.io"

  [[profileMode.buttons]]
  name = "Posts"
  url = "posts"

  [[profileMode.buttons]]
  name = "Tags"
  url = "tags"